### ISSUE TITLE
你好，本地图片报错

### ISSUE THREAD

**Issue by can-cc** [lujun9972/uimage#1]
cond: Symbol's function definition is void: url-file-file-readable-p

**Comment by can-cc** [comment]
不好意思，找到原因了
建议加上
(require 'iimage)

**Comment by lujun9972** [comment]
谢谢，确实是少require了文件，不过不是iimage，而是url－file。
uimage能够支持本地图片的显示，理论上不需要再开iimage了

**Comment by lujun9972** [comment]
我已经require了那些文件了,你可以更新下再试试

**Comment by can-cc** [comment]
got it
