### ISSUE TITLE
How can this image url format compatible with latex export

### ISSUE THREAD

**Issue by FelixHuoEZ** [lujun9972/uimage#4]
I find the url format supported is `http://xxx.com/xxx.png`, but when I export `org` to `latex`, there is only a url in the file.

So I want to know if it can support the url format like `file:http://xxx.com/xxx.png` to be compatible with latex export?

**Comment by FelixHuoEZ** [comment]
;; a by the way question: how to label this issue as `feature-request`?

**Comment by lujun9972** [comment]
May be you should customize the `uimage-mode-image-regex-alist` like this

``` elisp
(push `(,(concat 
          "\\(file:http://" uimage-mode-image-filename-regex "\\)") . 1)
      uimage-mode-image-regex-alist )
```

**Comment by FelixHuoEZ** [comment]
I am sorry for not express clearly.

I wanna use this format `[[file:http://xxx.com/xxx.png]]` instead of `file:http://xxx.com/xxx.png` .
So I should add something like your code.

But what is the number `2` after a period in your code mean? ;; I am a newbee, haha.

```
(defcustom uimage-mode-image-regex-alist
  `((,(concat "\\(`\\|\\[\\[\\|<)\\)?"
          "\\(\\(file://\\|ftp://\\|http://\\|https://\\)" uimage-mode-image-filename-regex "\\)"
          "\\(\\]\\]\\|>\\|'\\)?") . 2)
    (,(concat "\\(`\\|\\[\\[\\|<)\\)"
          "\\(" uimage-mode-image-filename-regex "\\)"
          "\\(\\]\\]\\|>\\|'\\)?") . 2))
```

**Comment by lujun9972** [comment]
As the doc-string described:NUM specifies which parenthesized expression in the regexp.

The content of the parenthesized expression is considered to be the image url.

**Comment by FelixHuoEZ** [comment]
Thx! I can just partly grasp it. So where could I find the description of the function and its parameter?

I cannot find the function `,()` with `C-h f`.

**Comment by lujun9972** [comment]
There is no function `,()` . you should see the macro `

> ` is a Lisp macro in ‘backquote.el’.
> 
> `STRUCTURE
> 
> Argument STRUCTURE describes a template to build.
> 
> The whole structure acts as if it were quoted except for certain
> places where expressions are evaluated and inserted or spliced in.
> 
> For example:
> 
> b              => (ba bb bc)      ; assume b has this value
> `(a b c)       => (a b c)     ; backquote acts like quote
> `(a ,b c)      => (a (ba bb bc) c)    ; insert the value of b
> `(a ,@b c)     => (a ba bb bc c)  ; splice in the value of b
> 
> Vectors work just like lists.  Nested backquotes are permitted.

**Comment by FelixHuoEZ** [comment]
I add the following code to my configuration file in order to match the expression `[[file:http://xxx.com/xxx.png]]` .

``` emacs-lisp
(push `(,(concat "\\(`\\|\\[\\[\\|<\\)?"
                   "\\(\\(file:http://\\)" uimage-mode-image-filename-regex "\\)"
                   "\\(\\]\\]\\|>\\|'\\)?") . 2)
        uimage-mode-image-regex-alist )
```

However, when I use `[[file:http://xxx.com/xxx.png]]` in my org file, the `http://xxx.com/xxx.png` in the expression will be convert to picture left the `[[file:  ]]` display before the picture.

![image](http://i.imgur.com/OGAHBfx.png)

**Comment by lujun9972** [comment]
Update `uimage` and try again

**Comment by lujun9972** [comment]
How is that work?

**Comment by FelixHuoEZ** [comment]
It works! Thx!
